### ISSUE TITLE
Ip fragmentation in p4 switch or host

### ISSUE THREAD

**Issue by x09326** [p4lang/p4factory#199] opened 2017-09-21 05:18 UTC
Hi, I'm doing an experiment. I want to send a video from a host to another.
When I use "sudo mn" as original mininet, it works.
But when I use p4 switch and host to send the file, I found that the packet will do the fragmentation, I saw that from wireshark.

So I don't know why the original mininet switch works without ip fragmentation but p4 switch not.
Could you know about that? And how do I solve this problem?
I want the p4 switch works like original mininet switch, it won't do the ip fragmentation.
Thanks.

**Comment by antoninbas** [comment] 2017-09-21 16:49
Duplicate of https://github.com/p4lang/behavioral-model/issues/443

**Closed as completed by antoninbas** 2017-09-21 16:49 UTC
